service:
  name: service
  identifier: service
  orgIdentifier: default
  projectIdentifier: namangoenka_CD
  serviceDefinition:
    spec:
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: gcpAuto
                imagePath: <+project.description>
                tag: <+input>
                digest: ""
                registryHostname: us.gcr.io
              identifier: a
              type: Gcr
    type: Kubernetes
